fix(sync-mainnet): disable replay temporarily
nervosnetwork/ckb-integration-test pull request #108
Opened 2022-04-20 15:51 UTC by chanhsu001

cause the whole process(sync + replay) takes more than 20 hours to finish
we disable `replay` step for now, and will add it again after we have a new way to take `sync + replay`

2022-04-21 08:20 UTC, doitian requested changes

2022-04-21 08:20 UTC, doitian commented on ckb-sync-mainnet/script/sync-mainnet.sh
> +      # ansible_ckb_replay
Just delete it

2022-04-21 09:10 UTC, chanhsu001 commented on ckb-sync-mainnet/script/sync-mainnet.sh
> +      # ansible_ckb_replay
deleted as suggestion.

2022-04-27 01:40 UTC, doitian approved these changes

2022-04-27 01:40 UTC, merged