fix(replay): fix PR95, correct syntax error
nervosnetwork/ckb-integration-test pull request #96
Opened 2022-03-13 12:54 UTC by chanhsu001

Fix PR #95 
correct syntax error, when workflow runs, error message as below:
shell: "CKB_LOG=error {{ ckb_workspace }}/ckb replay --tmp-target=/tmp --profile >> {{ ckb_data_dir }}/logs/run.log"
                         ^ here
There appears to be both 'k=v' shorthand syntax and YAML in this task. Only one syntax may be used.

the original statement as:
"CKB_LOG=error {{ ckb_workspace }}/ckb replay --tmp-target=/tmp --profile >> {{ ckb_data_dir }}/logs/run.log"
so change to 
"CKB_LOG='error' {{ ckb_workspace }}/ckb replay --tmp-target='/tmp' --profile >> {{ ckb_data_dir }}/logs/run.log"

But my question is: why yamllint can't detect this error? and the Ansible manual sucks.

2022-03-13 13:37 UTC, keroro520 requested changes

2022-03-13 13:37 UTC, keroro520 commented on ckb-sync-mainnet/ansible/playbook.yml
> +          shell: "CKB_LOG='error' {{ ckb_workspace }}/ckb replay --tmp-target='/tmp' --profile >> {{ ckb_data_dir }}/logs/run.log"
please use `environment` keyword: https://docs.ansible.com/ansible/latest/user_guide/playbooks_environment.html

2022-03-13 15:14 UTC, chanhsu001 commented on ckb-sync-mainnet/ansible/playbook.yml
> +          shell: "CKB_LOG='error' {{ ckb_workspace }}/ckb replay --tmp-target='/tmp' --profile >> {{ ckb_data_dir }}/logs/run.log"
modified as your suggestion, Thanks.

2022-03-14 02:32 UTC, doitian approved these changes

2022-03-14 04:29 UTC, keroro520 approved these changes

2022-03-14 04:30 UTC, merged